<#
Builds a static status page from the GitHub API: open agent-ready/idea issues
and the last few AHK Tests CI runs. Written to $OutDir/index.html for
actions/upload-pages-artifact. Uses GITHUB_TOKEN (read-only scope is enough).
#>
param(
    [Parameter(Mandatory)] [string]$Repo,        # e.g. "Flop0333/AutoHotkey"
    [Parameter(Mandatory)] [string]$Token,
    [Parameter(Mandatory)] [string]$OutDir
)

$ErrorActionPreference = "Stop"
$headers = @{
    Authorization = "Bearer $Token"
    Accept        = "application/vnd.github+json"
    "User-Agent"  = "ahk-dashboard"
}

function Get-Issues($label) {
    $uri = "https://api.github.com/repos/$Repo/issues?state=open&labels=$label&per_page=20"
    Invoke-RestMethod -Uri $uri -Headers $headers
}

function Get-Runs {
    $uri = "https://api.github.com/repos/$Repo/actions/workflows/ahk-tests.yml/runs?per_page=5"
    (Invoke-RestMethod -Uri $uri -Headers $headers).workflow_runs
}

$agentReady = Get-Issues "agent-ready"
$ideas = Get-Issues "idea"
$runs = Get-Runs

function Format-IssueRows($issues) {
    if (-not $issues -or $issues.Count -eq 0) {
        return "<tr><td colspan=3 class='empty'>None open</td></tr>"
    }
    ($issues | ForEach-Object {
        $labels = ($_.labels | ForEach-Object { $_.name }) -join ", "
        "<tr><td><a href='$($_.html_url)'>#$($_.number) $($_.title)</a></td><td>$labels</td><td>$($_.updated_at.Substring(0,10))</td></tr>"
    }) -join "`n"
}

function Format-RunRows($runs) {
    if (-not $runs -or $runs.Count -eq 0) {
        return "<tr><td colspan=3 class='empty'>No runs yet</td></tr>"
    }
    ($runs | ForEach-Object {
        $status = if ($_.conclusion) { $_.conclusion } else { $_.status }
        $cls = switch ($status) { "success" { "ok" }; "failure" { "fail" }; default { "pending" } }
        "<tr><td><a href='$($_.html_url)'>$($_.display_title)</a></td><td class='$cls'>$status</td><td>$($_.created_at.Substring(0,16).Replace('T',' '))</td></tr>"
    }) -join "`n"
}

$generated = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm 'UTC'")

$html = @"
<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><title>AutoHotkey repo status</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; background: #fafafa; }
  h1 { font-size: 1.4rem; } h2 { font-size: 1.1rem; margin-top: 2rem; border-bottom: 1px solid #ddd; padding-bottom: .3rem; }
  table { width: 100%; border-collapse: collapse; margin-top: .5rem; }
  td, th { text-align: left; padding: .4rem .5rem; border-bottom: 1px solid #eee; font-size: .9rem; }
  a { color: #0969da; text-decoration: none; } a:hover { text-decoration: underline; }
  .ok { color: #1a7f37; font-weight: 600; } .fail { color: #cf222e; font-weight: 600; } .pending { color: #9a6700; font-weight: 600; }
  .empty { color: #666; font-style: italic; }
  footer { margin-top: 2rem; font-size: .8rem; color: #666; }
</style></head>
<body>
<h1>AutoHotkey repo status</h1>

<h2>Recent CI runs</h2>
<table><tr><th>Run</th><th>Result</th><th>When</th></tr>
$(Format-RunRows $runs)
</table>

<h2>Agent-ready tasks</h2>
<table><tr><th>Issue</th><th>Labels</th><th>Updated</th></tr>
$(Format-IssueRows $agentReady)
</table>

<h2>Idea backlog</h2>
<table><tr><th>Issue</th><th>Labels</th><th>Updated</th></tr>
$(Format-IssueRows $ideas)
</table>

<footer>Generated $generated by .github/workflows/dashboard.yml</footer>
</body></html>
"@

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
Set-Content -Path (Join-Path $OutDir "index.html") -Value $html -Encoding utf8
